RooCodeInc/Roo-Code

src/extension.ts

* Use `rocket.png` to visually differentiate from `robot_panel_dark.png` and `robot_panel_light.png`
Use case:
* Install both https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline and https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev in VS code
* Instead of hovering over to visually differentiate between "Roo Cline" and "Cline"
* This may allow one to visually differentiate without hovering over

feat(extension.ts): use rocket icon

---

.changeset/funny-candles-exist.md
src/core/webview/ClineProvider.ts
src/core/webview/__tests__/ClineProvider.test.ts

A smarter version of this would probably leave something in the history to indicate that a message was deleted, but this seems like a reasonable place to start.

Allow deleting single messages

---

webview-ui/src/components/chat/ChatRow.tsx
webview-ui/src/index.css

Fix chat row alignment and dropdown scrollbar issues.
Manually tested in the webview.
The chat row alignment was not ideal, especially for longer messages. This change aligns items to `flex-start` for better readability.
Also, fixed a double scrollbar issue in dropdowns in the settings view.
**BEFORE:**
**AFTER:**
N/A

style: clean up chat row and api provider double scroll

---

.changeset/heavy-feet-judge.md
src/utils/__tests__/shell.test.ts
src/utils/shell.ts

Got a complaint from someone after upgrading to the latest version 
>Cannot read properties of undefined (reading 'path')
>This is a special error message for the latest version.
I'm asking them to try out a vsix with this change to confirm, but seems like more correct code in general.

Safer profile path check

---

src/core/Cline.ts
src/services/checkpoints/CheckpointService.ts
src/services/checkpoints/__tests__/CheckpointService.test.ts
webview-ui/src/components/settings/SettingsView.tsx

On Windows, when you redirect (pipe) the output of a command into a file in your repository, Windows will place (or keep) an exclusive lock on that file while the command is still running or immediately afterward. Then, if Git tries to move, rename, or otherwise manipulate that file (as happens in a stash operation), it fails because Windows won’t allow a locked file to be changed.
On Linux and macOS, open files aren’t locked the same way. A process can rename or even delete a file that is still “open” by another process without error—the file descriptor remains valid under the hood until the last process closes it. 
This screenshot below demonstrates the issue by:
- Creating and locking an untracked file by piping the output of another process to the file.
- Calling `git clean -f`
The …

Disable checkpoints on Windows

---

src/core/webview/ClineProvider.ts
src/shared/WebviewMessage.ts
webview-ui/src/components/prompts/PromptsView.tsx

This PR adds functionality to copy the system prompt to clipboard via a new UI button. It also refactors the system prompt generation logic into a separate function to avoid code duplication between preview and copy features.
The copy system prompt functionality has been tested through the following steps:
1. Manual Testing of Basic Functionality:
- Clicked the new copy button in the UI
- Verified the success notification "System prompt successfully copied to clipboard" appears
- Pasted the content into different text editors (VS Code, Notepad) to verify the clipboard content
- Verified the copied content matches the system prompt preview
2. Validation of Clipboard State:
- Tested clipboard isolation by:
- First copying a random text ("test123")
- Then using the system prompt copy feature …

Add 'copySystemPrompt' icon button next to Preview System Prompt

---

src/core/webview/ClineProvider.ts
src/services/mcp/McpHub.ts
src/shared/WebviewMessage.ts
webview-ui/src/components/mcp/McpView.tsx

- Added delete button with trash icon to MCP server rows
- Implemented confirmation dialog using existing Dialog component
- Added "deleteMcpServer" message type to WebviewMessage interface
- Added handler in ClineProvider to process deletion:
- Removes server from MCP settings file
- Closes server connection
- Updates UI to reflect changes
- Added user feedback with success/error notifications
- Ensured consistent modal design with rest of application
https://github.com/user-attachments/assets/b034904b-bee7-48ac-9053-bf85e076aac6

Added MCP server deletion with confirmation dialog

---

.changeset/sour-parents-hug.md
src/integrations/terminal/TerminalProcess.ts

Reverts RooVetGit/Roo-Code#1228
Cursor is still on 1.96.2 and this is fixed in 1.97.2 😞

Revert "Stop removing commas from terminal output"

---

e2e/src/suite/task.test.ts
src/core/webview/ClineProvider.ts

This commit fixes an issue where subtasks weren't properly reporting back to parent tasks when cancelled and resumed. Previously, when a subtask was cancelled and a new task was started with the same message, the parent task would incorrectly resume, causing unexpected behavior.
This fixes https://github.com/RooVetGit/Roo-Code/issues/1547
The fix:
1. Stores parent-child relationship information before cancelling a task
2. Restores this relationship after task reinitialization
3. Ensures parent tasks only resume when explicitly instructed to do so
This approach maintains the correct task hierarchy throughout the cancellation and resumption process, preventing parent tasks from automatically resuming when unrelated tasks with similar messages are started.
1. Create a task and tell it to …

fix: Preserve parent-child relationship when cancelling subtasks

---

webview-ui/src/components/ui/command.tsx
webview-ui/src/components/ui/dropdown-menu.tsx
webview-ui/src/components/ui/select.tsx

Forgot this from yesterday. All dropdown-like components should have the same look & feel.
| before | after |
| ------ | ----- |
|        |       |

Theme tweaks

---

src/core/Cline.ts
src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
src/core/prompts/tools/list-code-definition-names.ts

This PR fixes the 'cwd option must be a path to a directory' error when using list_code_definition_names with file paths.
- Add support for analyzing individual source files
- Update tool description to clarify file and directory usage
- Improve error messages for invalid paths
```xml
<list_code_definition_names>
<path>src/core/Cline.ts</path>
</list_code_definition_names>
```
Would produce an error:
```xml
<error>
Error parsing source code definitions: {"name":"Error","message":"The `cwd` option must be a path to a directory","stack":"Error: The `cwd` option must be a path to a directory\n ... "}
</error>
```
```xml
<list_code_definition_names>
<path>src/core/Cline.ts</path>
</list_code_definition_names>
```
Now produces useful code definitions:
```
122--4296 | export class Cline extends …
```

Fix list_code_definition_names to support files

---

src/core/tools/fetchInstructionsTool.ts
src/core/tools/listFilesTool.ts
src/core/tools/readFileTool.ts
src/core/tools/types.ts

Turns out it's pretty clean to remove the switch statement from these tools - just change `break` to `return`. Also noticed that we had the wrong type for one of the arguments, so fixed it.

Remove switch from tools

---

package-lock.json

npm warns me that there are 2 vulnerabilities (1 moderate, 1 high), so I use `npm audit fix`, and the high severity one was fixed:
- tar-fs 3.0.0-3.0.6 https://github.com/advisories/GHSA-pq67-2wwv-3xjx
There is only one moderate vulnerability now:
- esbuild <=0.24.2 https://github.com/advisories/GHSA-67mh-4wv8-2f99
Run `npm audit` first to check the vulnerabilities, then use `npm audit fix` to resolve them by updating dependencies. Then, run `npm audit` again, plus `git diff` to check the result.
Build the software as it was.

Update dependencies via `npm audit fix`

---

.changeset/poor-dolphins-brush.md
src/core/prompts/sections/__tests__/custom-instructions.test.ts
src/core/prompts/sections/custom-instructions.ts

Fix a bug not to resolve nested `.roo/rules` directories properly, such as `.roo/rules/subdir/file1.txt` or `.roo/rules/subdir/subdir2/file` rule files.
It seems to be intended to support nested directory structures, as `recursive` option is marked as `true` in the implementation. 
Sub directories  are quite helpful to organize multiple custom instructions files. It is nicer to support.
Use `Dirent#parentPath` instead of `dirPath` to resolve full path of each rule file.
This is because `dirPath` would be the path of `.roo/rules`, not sub directory path. So current path misses all subdirectories.
>  .then((files) => files.map((file) => path.resolve(dirPath, file.name)))
should be 
>  .then((files) => files.map((file) => path.resolve(file.parentPath, file.name)))
| before | after |
| ------ …

Fix a bug not to read rule files properly, under nested `.roo/rules` directories

---

.changeset/khaki-months-float.md
src/api/providers/openrouter.ts

I just noticed this when capturing OpenRouter requests in Postman.
When you create a new API profile it copies a bunch of potentially irrelevant settings, so we have to be a bit defensive here.

Omit reasoning params for non-reasoning models

---

webview-ui/src/components/chat/CommandExecution.tsx
webview-ui/src/components/chat/__tests__/CommandExecution.test.tsx
webview-ui/src/components/common/__mocks__/CodeBlock.tsx

Reverts RooVetGit/Roo-Code#3021
CC @KJ7LNW - This is breaking the webview; specifically the import of the BaseTerminal [here](https://github.com/RooVetGit/Roo-Code/pull/3021/files#diff-faf82daabb4d7d05255360bd653e63f8ec8332086d63d6070da53e8ea5826cbdR5). It's generally not safe to import from anything except `src/shared`.

Revert "feat: syntax highlighting terminal output with Shiki"

---

webview-ui/src/components/settings/About.tsx

In the "About Roo Code" section, the footer buttons (`Export`, `Import`, and `Reset`) did not wrap correctly on narrow screens. As a result, the layout broke and buttons overflowed the container. This PR fixes that issue and improves responsiveness on smaller viewports.
Applied CSS changes to enable proper wrapping of the footer buttons. Adjusted the container styling (e.g., `flex-wrap: wrap`, spacing adjustments) to ensure the buttons stay within bounds and stack gracefully on smaller widths.
| Before | After |
|--------|-------|
| ![before](https://github.com/user-attachments/assets/761dea2f-f86d-4a76-9e8c-dd0e94b9f661) | ![after](https://github.com/user-attachments/assets/1faac719-9bf5-478d-972c-78616b0e8621) |
- Open the "About Roo Code" section in the extension
- Resize the sidebar …

fix: wrap footer buttons in About section on narrow screens

---

.vscode/tasks.json

When running Roo from development build of vscode main emit the following error:
Error: Invalid problemMatcher reference: $esbuild-watch
This commit prevents that error by avoiding the use of $esbuild-watch
Please review this change before merging and make sure it works for you, I am not so familiar with the inner workings of vscode and npm, but this fix worked for me.
I am bisecting a problem in `vscode` itself which prevents Shift+CTRL+F5 from restarting the debug instance of Roo.it or some reason running the development build of `vscode` from their git tree produces that error, and this patch fixes a.
replace the built in watch with a simple check for started/finished 
1. code /path/to/roo-code-git
2. press F5
3. let it load
4. click back on main vscode (not the extension host)
5. …

build: prevent $esbuild-watch error

---

evals/apps/web/package.json
evals/pnpm-lock.yaml

This appears to break the evals web app.
Reverts RooVetGit/Roo-Code#3564

Revert "fix(deps): update nextjs monorepo to v15.3.2"

---

src/exports/interface.ts
src/exports/roo-code.d.ts
src/exports/types.ts
src/schemas/index.ts

[Roo-Code-Types v1.8.0](https://github.com/RooCodeInc/Roo-Code-Types/commit/e4ade0c3a16133b4bbfd183f898d09dfa20d1c2f)

Export ProviderName type to Roo-Code-Types

---

.github/workflows/marketplace-publish.yml

Bypass the pre-commit hook when pushing tags for the release.

Add --no-verify when pushing tags

---

.changeset/ten-bags-hang.md
src/api/transform/model-params.ts
src/shared/__tests__/api.test.ts
src/shared/api.ts
webview-ui/src/__tests__/ContextWindowProgress.test.tsx
webview-ui/src/components/chat/TaskHeader.tsx

This logic exists in `getModelParams` but not `getModelMaxOutputTokens`. As a follow-up I'll consolidate these. One primary goal of the refactor from #3870 was to have a single source of truth, but I never got around to update this function that the task header calls.

Fix max tokens in the task header

---

evals/packages/types/src/roo-code-defaults.ts
src/core/tools/readFileTool.ts
src/core/webview/ClineProvider.ts
webview-ui/src/components/settings/ContextManagementSettings.tsx
webview-ui/src/components/settings/SettingsView.tsx
webview-ui/src/context/ExtensionStateContext.tsx

Anecdotally Roo seems dumber when it doesn't read the whole file. I think full file reads are a safer default for now.

Default to full file reads

---

src/core/diff/strategies/multi-search-replace.ts
src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
src/core/prompts/tools/write-to-file.ts

Closes: #3941
This PR improves the tool descriptions for file editing operations to guide LLMs toward better tool selection. The main issue was that LLMs were frequently choosing `write_to_file` for file edits instead of more appropriate tools like `apply_diff`, `insert_content`, or `search_and_replace`, likely due to misleading tool descriptions.
**Key changes:**
- **write_to_file tool description**: Clarified primary use cases as creating new files or complete rewrites when intentionally required, reducing emphasis on full file reconstruction
- **apply_diff tool description**: Enhanced to emphasize "targeted modifications" and "precise, surgical edits", clarified support for multiple search/replace operations, and positioned as the preferred tool for targeted changes
- **Removed …

Improve tool descriptions to guide proper file editing tool selection

---

webview-ui/src/components/history/HistoryPreview.tsx
webview-ui/src/components/history/HistoryView.tsx
webview-ui/src/components/history/TaskItem.tsx
webview-ui/src/components/history/TaskItemFooter.tsx
webview-ui/src/components/history/TaskItemHeader.tsx
webview-ui/src/components/history/__tests__/HistoryView.test.tsx
webview-ui/src/components/history/__tests__/TaskItem.test.tsx

Introduces `TaskItem.tsx` and `TaskItemHeader.tsx` to centralize and
standardize the rendering of history entries. `TaskItem` handles the
overall structure for "compact" (Preview) and "full" (HistoryView)
variants. `TaskItemHeader` consolidates all metadata (timestamp, tokens,
cost, cache, file size) into a single, consistent line above the task
content, enhancing visual clarity and reducing UI clutter.
This refactor significantly simplifies `HistoryPreview.tsx` and
`HistoryView.tsx`. Approximately 314 lines of previous rendering logic
were removed from these components and replaced by 242 lines in the new,
focused, and reusable `TaskItem` and `TaskItemHeader` components,
resulting in a net reduction and improved maintainability.
Most importantly, rendering logic happens in one place.
Key …

Unify history item UI with TaskItem and TaskItemHeader

---

webview-ui/src/components/chat/ChatTextArea.tsx
webview-ui/src/components/chat/__tests__/ChatTextArea.test.tsx
webview-ui/src/components/chat/hooks/usePromptHistory.ts

Fixes #4139
This PR implements hybrid prompt history navigation using arrow up/down keys in the chat input field, providing an intuitive
terminal-like experience that adapts to the user's current context.
- **Active conversation**: Navigate through recent conversation messages (newest first)
- **Starting fresh**: Navigate through task history from previous sessions (newest first)
- Automatically detects if user is in an active conversation vs starting fresh
- Seamlessly switches between `clineMessages` and `taskHistory` as data sources
- Resets navigation position when switching between history sources
- **Arrow Up**: Navigate to previous (older) prompts
- **Arrow Down**: Navigate to next (newer) prompts or return to current input
- Only triggers when cursor is at first/last line of …

feat: Navigate prompt history in prompt field via arrow up/down (#4139)

---

.roo/rules-issue-fixer/1_Workflow.xml

Fixing the issue fixer workflow order

refactor: reorganize implementation plan step in workflow

---

webview-ui/src/components/chat/McpExecution.tsx
webview-ui/src/components/mcp/McpToolRow.tsx
webview-ui/src/components/mcp/__tests__/McpToolRow.spec.tsx

Fixes #4993
This PR addresses two issues with the MCP tool eye icon:
1. The eye icon was showing the wrong state (showed eye when enabled, should show eye-closed)
2. The eye icon was appearing in chat context where it shouldn't be visible
- Added `isInChatContext` optional prop to `McpToolRow` component in [`webview-ui/src/components/mcp/McpToolRow.tsx`](webview-ui/src/components/mcp/McpToolRow.tsx)
- Fixed the eye icon state logic to show `codicon-eye-closed` when enabled and `codicon-eye` when disabled
- Conditionally hide the eye button when `isInChatContext` is true
- Updated [`webview-ui/src/components/chat/McpExecution.tsx`](webview-ui/src/components/chat/McpExecution.tsx) to pass `isInChatContext={true}` when rendering McpToolRow
- Added comprehensive tests to verify the new …

fix: resolve MCP tool eye icon state and hide in chat context (#4993)

---

.roo/rules-translate/001-general-rules.md

This PR updates the translation workflow guidelines to use a more efficient approach that reduces unnecessary file reads and context token usage.
The improved workflow:
- Uses `search_files` to find JSON keys that are near new keys in English translations
- Creates proper context for `apply_diff` without reading every file
- Only reads specific files when their structure differs from the expected pattern
- Validates changes with the missing translations script as the final step
This approach has been successfully tested with the errorBoundary translations and significantly reduces the number of file reads required.
1. Follow the updated workflow in the translation rules when adding new translations
2. Verify that you can successfully add translations without reading every file …

Improve translation workflow to avoid unnecessary file reads

---

.roo/rules/rules.md

When running vitest without the run parameter, it enters watch mode and waits for user input (like pressing q to quit), causing tests to hang in the terminal.
This PR updates the documentation in `.roo/rules/rules.md` to specify using `npx vitest run` instead of just `npx vitest` to ensure tests run to completion without requiring user interaction.
Fixes: #5992
1. Check the updated documentation in `.roo/rules/rules.md`
2. Verify that the command now includes the `run` parameter: `npx vitest run <relative-path-from-workspace-root>`
3. Try running a test with and without the `run` parameter to observe the difference in behavior:
- With `run`: Test runs and completes automatically
- Without `run`: Test enters watch mode and waits for user input
Discord: KJ7LNW

fix: add run parameter to vitest command in rules

---

packages/types/src/__tests__/provider-settings.test.ts
packages/types/src/provider-settings.ts
src/core/task/Task.ts

This PR updates the API protocol handling to properly support bedrock provider while maintaining special handling for vertex provider with Claude models.
1. **Added 'bedrock' to ANTHROPIC_STYLE_PROVIDERS**: Bedrock provider now uses Anthropic-style API protocol by default
2. **Restored Claude model checking for vertex provider**: The vertex provider continues to check if the model contains 'claude' (case-insensitive) to determine API protocol
3. **Updated tests**: Added comprehensive tests for the updated functionality
4. **Updated Task.ts**: Restored the modelId parameter passing to getApiProtocol
Fixes: #6004

fix: add bedrock to ANTHROPIC_STYLE_PROVIDERS and restore vertex Claude model checking

---

src/services/code-index/processors/file-watcher.ts
src/services/code-index/processors/scanner.ts
src/services/code-index/vector-store/qdrant-client.ts

This PR fixes Qdrant deletion operations that were failing with HTTP 400 "Bad Request" errors by using indexed `pathSegments` fields instead of the non-indexed `filePath` field.
The `deletePointsByMultipleFilePaths` method was attempting to filter points using the `filePath` field, but this field is not indexed in Qdrant collections. Only `pathSegments.0` through `pathSegments.4` fields have indexes. When Qdrant receives a filter query on a non-indexed field, it returns a 400 Bad Request error: "Index required but not found for 'filePath'".
Updated `deletePointsByMultipleFilePaths` in `qdrant-client.ts` to:
- Build filters using `pathSegments` fields (which are indexed) instead of `filePath`
- Match the exact path by creating filters for each segment of the file path
- Use the same …

fix: handle Qdrant deletion errors gracefully to prevent indexing interruption

---

webview-ui/src/components/chat/ChatView.tsx

This PR fixes the scroll jitter issue introduced in PR #6697 by reverting only the problematic scrolling method change.
PR #6697 introduced scroll jitter during streaming, particularly noticeable with code blocks. Through systematic testing, we identified that the change from `scrollTo` to `scrollToIndex` was the root cause.
This PR changes only the scroll implementation back from `scrollToIndex` to `scrollTo`, keeping all memory optimizations from PR #6697 intact.
- Replace `scrollToIndex` with `scrollTo` in both `scrollToBottomSmooth` and `scrollToBottomAuto` functions
- Remove dependency on `groupedMessages.length` from the scroll functions
- Use `Number.MAX_SAFE_INTEGER` to scroll to bottom
The `scrollToIndex` method tries to calculate and jump to specific message indices while …

fix: Replace scrollToIndex with scrollTo to fix scroll jitter

---

webview-ui/src/components/chat/ChatView.tsx

This PR fixes an issue where user messages were disappearing when selecting follow-up choices at choice prompts.
When users typed a message at a choice prompt and then selected a follow-up suggestion, their typed message was being cleared and lost. The message was not visible in the chat history and was not available in the up-key message history.
The fix preserves the user's input value in the text area after sending the follow-up choice message. This ensures that what the user typed remains visible and accessible.
- Modified the `handleFollowUpClick` function in `ChatView.tsx` to preserve the input value when sending follow-up choices
- Added `inputValue` to the dependency array of the `handleFollowUpClick` callback
- Tested that user input is preserved when selecting follow-up choices …

fix: preserve user input when selecting follow-up choices

---

src/utils/__tests__/tiktoken.spec.ts
src/utils/tiktoken.ts

Closes: https://github.com/RooCodeInc/Roo-Code/issues/7539
Add `disabled_specials = []` to `encoder.encode(...)` parameters in `tiktoken.ts` to guarantee that specials do not break task execution.
Added a test to `tiktoken.spec.ts` to check this case.
Does this PR necessitate updates to user-facing documentation?
ilintar on Discord

fix: special tokens should not break task processing

---

webview-ui/src/components/welcome/WelcomeView.tsx

This PR improves the styling and readability of the WelcomeView component, addressing issues with excessive padding and bold text that made the interface look cluttered.
- **Reduced excessive padding**: Changed from `p-16` to `p-6` for better space utilization
- **Removed excessive bold text**: Used `font-medium` instead of `font-bold` for a cleaner look
- **Made components more compact**: 
- Reduced provider card padding
- Smaller icons (32x32px instead of 40x40px)
- Changed border radius from `rounded-lg` to `rounded-md`
- **Improved text visibility**:
- Increased introduction text size from `text-sm` to `text-base`
- Better color contrast using `text-vscode-foreground`
- Centered the main greeting title
- **Enhanced visual hierarchy**: Added proper spacing and text sizing throughout
- …

Fix: Improve WelcomeView styling and readability

---

apps/web-roo-code/src/app/page.tsx

Updated the homepage to reflect expanded capabilities beyond the editor:
- Changed headline to "Your AI-Powered Dev Team, in Your Editor and Beyond"
- Applied gradient styling to "and Beyond" text for visual consistency
- Updated tagline to mention both editor and cloud development capabilities
- Modified headline structure to split across multiple lines with gradient effect on "and Beyond"
- Updated tagline from "Supercharge your editor" to "Supercharge your software development"
- Extended description to include "in your editor and in the cloud"
- View homepage at localhost:3000
- Verify headline displays correctly with gradient on "and Beyond"
- Confirm tagline text updates are visible
- Check responsive design on different screen sizes

feat(web): update homepage headline and tagline for remote control capabilities
